on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
  
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: dkunzevich/prueba-gha:latest

    - name: deploy to k8s
      uses: wahyd4/kubectl-helm-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: |
          set image --record deployment/my-app prueba-gha=${{ github.repository }}:${{ github.sha }}
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm upgrade --install postgres -n data bitnami/postgresql        