on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ github.repository }}
    - run: docker push ${{ env.IMAGE }}:${{ env.GIT_SHA }}
